// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_render.ts";
import * as $1 from "./routes/docs.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Demo3D.tsx";

const manifest = {
  routes: {
    "./routes/_render.ts": $0,
    "./routes/docs.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Demo3D.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
